[workspace]

[package]
name = "multithreading"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
cognition = { path = "../.." }
time = { path = "../time" }
serde = "1.0"