[workspace]

[package]
name = "graphemes"
version = "0.1.1"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cognition = { path = "../.." }
unicode-segmentation = "1.12.0"
