[workspace]

[package]
name = "time"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
cognition = { path = "../.." }
serde = { version = "1.0", features = ["derive"] }